server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 120s # 세션 타임아웃
  tomcat:
    connection-timeout: 120000 # 120초

spring:
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${LLAMA_API_KEY}
      base-url: ${LLM_BASE_URL:https://integrate.api.nvidia.com/v1}
      chat:
        model: ${LLM_MODEL:meta/llama-3.2-11b-vision-instruct}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10




  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

      logging:
        level:
          org:
            hibernate:
              SQL: debug
              type: trace
          com:
            todoing: debug

  jwt:
    secret: ${JWT_SECRET}
    token:
      access-token-expire-time: ${JWT_ACCESS_EXPIRE}
      refresh-token-expire-time: ${JWT_REFRESH_EXPIRE}

    data:
      redis:
        host: ${REDIS_HOST:redis}
        port: ${REDIS_PORT:6379}


kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URI}

kakaopay:
  cid: ${KAKAOPAY_CID}
  secret_key: ${KAKAOPAY_SECRET_KEY}
  redirect:
    whitelist:
      - https://todooungi.netlify.app/payment
      - http://localhost:5173/payment
      - http://localhost:8080/payment


